#!/usr/bin/env python
from argparse import ArgumentParser

def get_parser():
	parser = ArgumentParser()
    sub = parser.add_subparsers(help='sub-command help')

    ht = 'Usage: status'
    status = sub.add_parser('status', help=ht)
    status.add_argument('--id', dest='identifier', help='first few chars of location_id or '
                                                     'event_owner_id, checks for uniqueness first')
    status.set_defaults(func=status)

    ht = 'Usage: configure'
    configure = sub.add_parser('configure', help=ht)
    configure.add_argument('--id', dest='identifier', help='first few chars of location_id or '
                                                     'event_owner_id, checks for uniqueness first')
    configure.set_defaults(func=configure)
    return parser

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    args.func(args)